Домашнее задание №10 «Обработка данных сенсора движения»
chepsel/home_work_basic pull request #11
Opened 2024-03-03 14:11 UTC by chepsel

- [x] Создайте горутину для имитации считывания данных с сенсора и передачи их в канал. Данные должны считываться в течение 1 минуты. 
- [x] Создайте горутину для обработки данных. Для каждых 10 полученных значений вычисляется среднее арифметическое и отправляется в канал с обработанными данными. 
- [x] Главная горутина будет получать обработанные данные из канала и выводить их на экран.
- [x] Напишите юнит тесты на реализованные функции;

2024-03-03 19:16 UTC, vladislavmass requested changes

2024-03-03 19:16 UTC, vladislavmass commented on hw10_motion_sensor/main.go
> +		chanelStat <- PrintMemUsage()
Считывание датчиков должно заниматься ровно 1 минуту. Предположим для примера что  `PrintMemUsage()` выполняется за 100 миллисекунд, ну например мы ходим за данными датчика по сети. Итого получаем что метод будет работать 60*100=6000 миллисекунд. или 6 секунд. Итого время работы генератора 1 минута и 6 секунд. А если метода  `PrintMemUsage()`  будет работать за от 60 мс до 300 мс? Попробуйте переписать метод что бы он не зависел от времени работы. Рекомендую для этого использовать select и time.After

2024-03-03 19:16 UTC, vladislavmass commented on hw10_motion_sensor/main.go
> +	var m runtime.MemStats
В данном случае лучше будет использовать генератор случайных чисел

2024-03-03 19:16 UTC, vladislavmass commented on hw10_motion_sensor/main.go
> +	go printStat(ageregatedStat)
Этот метод не нужно запускать в отдельном потоке

2024-03-03 19:16 UTC, vladislavmass commented on hw10_motion_sensor/main.go
> +	for {
Данный код выглядит как самописный аналог range for chanel, рекомендую переписать код на него

2024-03-03 19:16 UTC, vladislavmass commented on hw10_motion_sensor/main.go
> +			close(ageregatedStat)
Каналы обычно закрывают через `defer`, так как он гарантирует закрытие канала при выходе из метода

2024-03-05 18:53 UTC, vladislavmass approved these changes

2024-03-05 18:53 UTC, vladislavmass commented on hw10_motion_sensor/main.go
> +		case <-time.After(time.Second):
Если очень хотелось сделать отправку данных раз в секунду(хотя не понимаю откуда мысль что отправка должна быть раз в секунду ), то было бы лучше использовать time.Ticker

2024-03-05 20:03 UTC, chepsel commented on hw10_motion_sensor/main.go
> +		case <-time.After(time.Second):
Предположил что устраивать ddos консоли немного излишне) 
Поправил - убрал все таймеры и стопоры между проверкой\отправкой в канал.

2024-03-06 07:30 UTC, vladislavmass commented on hw10_motion_sensor/main.go
> +		case <-time.After(time.Second):
Ну DDOS точно устроить не выйдет, так как первая D это распределенная, да и сама по себе консоль не такая медленная. Если консоль начинают тормозить, то можно перенаправить вывод в файл и тогда тормозов заметно не будет

2024-03-06 07:31 UTC, vladislavmass approved these changes

2024-03-06 07:47 UTC, merged